server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.wit.springcloud.entities         # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: gatherwitcloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://121.196.218.189:3306/cloudDB02              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200   
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gatherwitcloud-dept8002                      #服务名称修改  自定义服务名称信息
    prefer-ip-address: true                                   #访问路径可以显示IP地址
      
info: 
  app.name: juzhi-gatherwitcloud                          #点击Eurake中注册的微服务要其显示信息的配置
  company.name: www.wit.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$     
      
      
      
      
      
      
      
      
      
      
      
      
      
      